# LAB 1: Matrix and Vector Computations in python
In this lab you will use python to study the following topics:

- How to create matrices and vectors in python.

- How to manipulate matrices in python and create matrices of special types.

- How to add matrices and multiply a vector by a matrix by python.

- Solving System of Linear Equations Using Gaussian Elimination.

- Matrix Multiplication using Different views.

# First: you should run this cell

In [2]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

import sympy as sym

# Question 1 :Declaring scalars, vectors, and matrices

a) Use [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) to declare the following:

1. A scalar $s = 5$
2. A vector $v = \begin{bmatrix} 5  \\ -2 \\ 4  \\ \end{bmatrix}$
3. A matrix $A = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ 7 & 8 & 9  \\ \end{bmatrix}$
4. A matrix $B = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ \end{bmatrix}$
5. A matrix $C = \begin{bmatrix} 1 & 2   \\ 3 & 4  \\ 5 & 6   \\ \end{bmatrix}$

In [2]:
# scalar s
s = np.array(5)
# vector v
v = np.array([[5],[-2],[4]])
# matrix A
A = np.arange(1,10).reshape(3,3)
# matrix B 
B = np.arange(1,7).reshape(2,-1)
# matrix C 
C = np.arange(1,7).reshape(-1,2)

print(f's = {s}\n')
print(f'V =\n {v}\n')
print(f'A =\n {A}\n')
print(f'B =\n {B}\n')
print(f'C =\n {C}\n')



s = 5

V =
 [[ 5]
 [-2]
 [ 4]]

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

B =
 [[1 2 3]
 [4 5 6]]

C =
 [[1 2]
 [3 4]
 [5 6]]



In [2]:
#type your code here:


s = 5

v =
 [[ 5]
 [-2]
 [ 4]]

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

B =
 [[1 2 3]
 [4 5 6]]

C =
 [[1 2]
 [3 4]
 [5 6]]



b) Print the data type of $s, v,$ and $A$ using `type` command in python.

In [3]:
print('type(s) = ',type(s),"\n")
print('type(v) = ',type(v),"\n")
print('type(A) = ',type(A),"\n")


type(s) =  <class 'numpy.ndarray'> 

type(v) =  <class 'numpy.ndarray'> 

type(A) =  <class 'numpy.ndarray'> 



In [3]:
#type your code here:


type(s) = <class 'numpy.ndarray'>

type(v) = <class 'numpy.ndarray'>

type(A) = <class 'numpy.ndarray'>



c) Using [numpy.shape](https://numpy.org/devdocs/reference/generated/numpy.shape.html) or `A.shape` print the shape of $s, v, A, B,$ and $C$.

In [4]:
print('s.shape = ',s.shape,"\n")
print('v.shape = ',v.shape,"\n")
print('A.shape = ',A.shape,"\n")
print('B.shape = ',B.shape,"\n")
print('C.shape = ',C.shape,"\n")


s.shape =  () 

v.shape =  (3, 1) 

A.shape =  (3, 3) 

B.shape =  (2, 3) 

C.shape =  (3, 2) 



In [4]:
#type your code here:


s.shape = ()

v.shape = (3, 1)

A.shape = (3, 3)

B.shape = (2, 3)

C.shape = (3, 2)



d) To access a given entry in the `numpy array` put the `row number - 1` and `column number - 1` in square brackets following the array name. Ex `a32 = A[2, 1]`.
- Print the value of the third row and the second column of the matrix $A$.
- Change it to $10$.
- Print the matrix A to check the entry is changed.

In [5]:
print("A[2,1] = ",A[2,1],"\n")
A[2,1] = 10
print("A = \n",A)

A[2,1] =  8 

A = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]


In [63]:
#type your code here:


A[2,1] =  8 

A = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]


e)To access a whole row or column of a matrix, use the colon operator. For example, `A[:, [1]]` is the second column of A, while `B[[1], :]` is the second row of B.

In [6]:
print("A[:, [1]]= \n",A[:, [1]],"\n")
print("B[[1], :]= \n",B[[1], :])

A[:, [1]]= 
 [[ 2]
 [ 5]
 [10]] 

B[[1], :]= 
 [[4 5 6]]


In [70]:
#type your code here:


A[:, [1]]= 
 [[ 2]
 [ 5]
 [10]] 

B[[1], :]= 
 [[4 5 6]]


f) Type each of the following commands that generate special matrices:
- `np.eye(4), np.zeros(3), np.zeros((3, 1)), np.zeros((3, 5)), np.ones((2, 3)), and np.diag([4, 5, 6, 7])`

In [7]:
eye = np.eye(4)
zeros_1 = np.zeros(3)
zeros_2 = np.zeros((3,1))
zeros_3 = np.zeros((3,5))
ones = np.ones((2,3))
diag = np.diag([4, 5, 6, 7])

print("np.eye(4) = \n",eye,"\n")
print("np.zeros(3) = = \n",zeros_1,"\n")
print("np.zeros(3, 1) = \n",zeros_2,"\n")
print("np.zeros(3, 5) = \n",zeros_3,"\n")
print("np.ones((2,3)) = \n",ones,"\n")
print("np.diag([4, 5, 6, 7]) = \n",diag,"\n")





np.eye(4) = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

np.zeros(3) = = 
 [0. 0. 0.] 

np.zeros(3, 1) = 
 [[0.]
 [0.]
 [0.]] 

np.zeros(3, 5) = 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

np.ones((2,3)) = 
 [[1. 1. 1.]
 [1. 1. 1.]] 

np.diag([4, 5, 6, 7]) = 
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]] 



In [7]:
#type your code here:


np.eye(4) =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

np.zeros(3) =
 [0. 0. 0.]

np.zeros(3, 1) =
 [[0.]
 [0.]
 [0.]]

np.zeros(3, 5) =
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

np.ones(2, 3) =
 [[1. 1. 1.]
 [1. 1. 1.]]

np.diag([4 5 6 7]) =
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


# Question 2. Vectors Addition, Scaling, and dot product

a) Declare vectors $v1 = \begin{bmatrix} 1  \\ 2 \\ 7  \\ 4 \\ \end{bmatrix}$ and $v2 = \begin{bmatrix} 4  \\ 3 \\ 6  \\ 8 \\ \end{bmatrix}$

- Addition: $v1 + v2$
- Subtraction: $v1 - v2$
- Scaling by a number: $3 * v1$
- Scaling by a number: $v1 / 2$

In [8]:
v1 = np.array([[1],[2],[7],[4]])
v2 = np.array([[4],[3],[6],[8]])
add = v1 + v2
sub = v1 - v2
scalling_1 = 3 * v1
scalling_2 = v1/2

print("v1 = \n",v1,"\n")
print("v2 = \n",v2,"\n")
print("v1 + v2 = \n",add,"\n")
print("v1 - v2 = \n",sub,"\n")
print("3*v1 = \n",scalling_1,"\n")
print("v1/2 = \n",scalling_2,"\n")



v1 = 
 [[1]
 [2]
 [7]
 [4]] 

v2 = 
 [[4]
 [3]
 [6]
 [8]] 

v1 + v2 = 
 [[ 5]
 [ 5]
 [13]
 [12]] 

v1 - v2 = 
 [[-3]
 [-1]
 [ 1]
 [-4]] 

3*v1 = 
 [[ 3]
 [ 6]
 [21]
 [12]] 

v1/2 = 
 [[0.5]
 [1. ]
 [3.5]
 [2. ]] 



In [8]:
#type your code here:


v1 =
 [[1]
 [2]
 [7]
 [4]]

v2 =
 [[4]
 [3]
 [6]
 [8]]

v1 + v2 =
 [[ 5]
 [ 5]
 [13]
 [12]]

v1 - v2 =
 [[-3]
 [-1]
 [ 1]
 [-4]]

3*v1 =
 [[ 3]
 [ 6]
 [21]
 [12]]

v1/2 =
 [[0.5]
 [1. ]
 [3.5]
 [2. ]]



b) Find the dot product between the two vectors $v1$ and $v2$ using the following:

- [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
- `v1.T @ v2`

In [9]:
print("Using numpy.dot = \n",np.dot(v1.T,v2),"\n")
print("Using numpy.matmul = \n",np.matmul(v1.T,v2),"\n")
print("Using @ = \n",v1.T@v2,"\n")


Using numpy.dot = 
 [[84]] 

Using numpy.matmul = 
 [[84]] 

Using @ = 
 [[84]] 



In [9]:
#type your code here:


Using numpy.dot =
 [[84]]

Using numpy.matmul =
 [[84]]

Using @ =
 [[84]]



c) Find the length of the vectors $v1$ and $v2$.
- Using [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
- Using the dot product and [numpy.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)


In [10]:
print("length of v1 Using numpy.linalg.norm = \n",np.linalg.norm(v1),"\n")  
print("length of v2 Using numpy.linalg.norm = \n",np.linalg.norm(v2),"\n")  
print("length of v1 Using the dot product and numpy.sqrt = \n",np.sqrt(np.sum(v1**2)),"\n")  
print("length of v2 Using the dot product and numpy.sqrt = \n",np.sqrt(np.sum(v2**2)),"\n")  

length of v1 Using numpy.linalg.norm = 
 8.366600265340756 

length of v2 Using numpy.linalg.norm = 
 11.180339887498949 

length of v1 Using the dot product and numpy.sqrt = 
 8.366600265340756 

length of v2 Using the dot product and numpy.sqrt = 
 11.180339887498949 



In [10]:
#type your code here:


length of v1 Using numpy.linalg.norm =
 8.366600265340756

length of v2 Using numpy.linalg.norm =
 11.180339887498949

length of v1 Using the dot product and numpy.sqrt =
 [[8.36660027]]

length of v2 Using the dot product and numpy.sqrt =
 [[11.18033989]]



d) Show that the vectors $u = \begin{bmatrix} 3  \\ 2 \\ -1  \\ 4 \\ \end{bmatrix}$ and $v = \begin{bmatrix} 1  \\ -1 \\ 1  \\ 0 \\ \end{bmatrix}$ are orthogonal.


In [11]:
u = np.array([[3],[2],[-1],[4]])
 v = np.array([[1],[-1],[1],[0]])
print("u.T @ v = \n",u.T@v)


u.T @ v = 
 [[0]]


In [11]:
#type your code here:


u.T @ v =
 [[0]]



# Question 3. Matrix Addition and Matrix-Vector Multiplication

Declare vectors $u$ and $v$ and matrices $A$ and $B$ as following:
- $u = \begin{bmatrix} 2  \\ 7 \\ 2 \\ \end{bmatrix}$, $v = \begin{bmatrix} 8  \\ 2 \\ 4 \\ \end{bmatrix}$
- $A = \begin{bmatrix} 7 & 3 & 5  \\ 4 & 6 & 2 \\ \end{bmatrix}$, $B = \begin{bmatrix} 0 & 6 & 4  \\ 2 & 3 & 0 \\ \end{bmatrix}$

a) Calculate the following using python.

- $A+B$
- $B+A$
- $3A$
- $6B$
- $2(3B)$
- $6A+15B$
- $3(2A+5B)$
- $(3A^T)^T$

In [15]:
u = np.array([[2],[7],[2]])
v = np.array([[8],[2],[4]])
A = np.array([[7,3,5],[4,6,2]])
B = np.array([[0,6,4],[2,3,0]])

print("u = \n",u,"\n")
print("v = \n",v,"\n")
print("A = \n",A,"\n")
print("B = \n",B,"\n")
print("A + B = \n",A+B,"\n")
print("B + A = \n",B+A,"\n")
print("3A = \n",3*A,"\n")
print("6B = \n",6*B,"\n")
print("2(3B) = \n",2*(3*B),"\n")
print("6A + 15B = \n",6*A + 15*B,"\n")
print("3(2A + 5B) = \n",3*(2*A+5*B),"\n")
print("(3A^T)^T = \n",(3*A.T).T,"\n")




u = 
 [[2]
 [7]
 [2]] 

v = 
 [[8]
 [2]
 [4]] 

A = 
 [[7 3 5]
 [4 6 2]] 

B = 
 [[0 6 4]
 [2 3 0]] 

A + B = 
 [[7 9 9]
 [6 9 2]] 

B + A = 
 [[7 9 9]
 [6 9 2]] 

3A = 
 [[21  9 15]
 [12 18  6]] 

6B = 
 [[ 0 36 24]
 [12 18  0]] 

2(3B) = 
 [[ 0 36 24]
 [12 18  0]] 

6A + 15B = 
 [[ 42 108  90]
 [ 54  81  12]] 

3(2A + 5B) = 
 [[ 42 108  90]
 [ 54  81  12]] 

(3A^T)^T = 
 [[21  9 15]
 [12 18  6]] 



In [12]:
#type your code here:


u =
 [[2]
 [7]
 [2]]

v =
 [[8]
 [2]
 [4]]

A =
 [[7 3 5]
 [4 6 2]]

B =
 [[0 6 4]
 [2 3 0]]

A + B =
 [[7 9 9]
 [6 9 2]]

B + A =
 [[7 9 9]
 [6 9 2]]

3A =
 [[21  9 15]
 [12 18  6]]

6B =
 [[ 0 36 24]
 [12 18  0]]

2(3B) =
 [[ 0 36 24]
 [12 18  0]]

6A + 15B =
 [[ 42 108  90]
 [ 54  81  12]]

3(2A + 5B) =
 [[ 42 108  90]
 [ 54  81  12]]


 (3A^T)^T = 
 [[21  9 15]
 [12 18  6]]


b) To obtain the matrix-vector product $Au$ using python, type `A @ u`. Calculate the following:

- $Au+Av$
- $A(u+v)$
- $(A+B)u$
- $Au+Bu$
- $A(3u)$
- $3A(u)$

In [31]:
print("Au + Av = \n",(A@u) + (A@v),"\n")
print("A(u + v) = \n",A@(u + v),"\n")
print("(A + B)u = \n",(A + B)@u,"\n")
print("Au + Bu = \n",A@u + B@u,"\n")
print("A(3u) = \n",A@(3*u),"\n")
print("3A(u) = \n",3*A@(u),"\n")


Au + Av = 
 [[127]
 [106]] 

A(u + v) = 
 [[127]
 [106]] 

(A + B)u = 
 [[95]
 [79]] 

Au + Bu = 
 [[95]
 [79]] 

A(3u) = 
 [[135]
 [162]] 

3A(u) = 
 [[135]
 [162]] 



In [13]:
#type your code here:


Au + Av =
 [[127]
 [106]]

A(u + v) =
 [[127]
 [106]]

(A + B)u =
 [[95]
 [79]]

Au + Bu =
 [[95]
 [79]]

A(3u) =
 [[135]
 [162]]

3A(u) =
 [[135]
 [162]]



# Question 4. Gaussian Elimination and Reduced Row-Echelon Form

You will see a step-by-step example of the row operations that transform a matrix $A$ into its reduced row echelon form $R = rref(A)$. In this demonstration, each pivot is chosen to be the largest in its column (for numerical stability), so extra row interchanges are used. Since $rref(A)$ is uniquely determined by $A$, this does not affect the final answer.

The built in [rref](https://docs.sympy.org/latest/tutorial/matrices.html#rref) method `sympy.rref()` method just search for the method and its output to deal with the code.

#### (a) Generate and display a $3 \times 4$ matrix $A$ with random integer entries 

In [37]:
#type your code here:
A = np.fix((10*(np.random.rand(3,4))))
print("\n A = \n", A)


 A = 
 [[6. 0. 7. 3.]
 [8. 9. 8. 8.]
 [8. 4. 4. 6.]]


- To transform $A$ into $R = rref(A)$, start with $R = A$.
- Normalize the first row of R to get R(1st row, 1st column) = 1

    - `R = A`
    - `R[0,:] = R[0, :] / R[0, 0]`

(note the use of the colon to operate on whole rows of the matrix). 

<div class="alert alert-block alert-warning">If your random matrix happens to have A(1, 1) = 0, then interchange rows to get a nonzero entry in the (1, 1) position before doing the calculation above.</div>

- Now subtract a multiple of the first row of R from the second row to make R(2, 1) = 0:

    - `R[1, :] = R[1, :] - R[1, 0] * R[0, :]`

- Repeat this procedure to make R(3, 1) = 0:

    - `R[2, :] = R[2, :] - R[2, 0] * R[0, :]`

The first column of your matrix $R$ should now be the same as the first column of $rref(A)$.

In [41]:
R = A
R[0,:] = R[0, :] / R[0, 0]
R[1, :] = R[1, :] - R[1, 0] * R[0, :]
R[2, :] = R[2, :] - R[2, 0] * R[0, :]
print("R = \n",R)

R = 
 [[ 1.          0.          1.16666667  0.5       ]
 [ 0.          9.         -1.33333333  4.        ]
 [ 0.          4.         -5.33333333  2.        ]]


In [15]:
#type your code here:



 R = 
 [[ 1.     0.     0.5    0.125]
 [ 0.     6.    -1.     6.25 ]
 [ 0.     1.     6.     0.   ]]


#### (b)Operate on $R$ by the same method as in (a) to obtain the second column of $rref(A)$. First normalize row $2$ of $R$, then subtract multiples of row $2$ from rows $1$ and $3$ to put zeros in the (1, 2) and (3, 2) positions. Be sure to refer to the entries in your matrix symbolically as was done in part (a)

In [42]:

R[1,:] = R[1, :] / R[1 ,1]
R[2, :] = R[2, :] - R[2, 1] * R[1, :]
print("R = \n",R)

R = 
 [[ 1.          0.          1.16666667  0.5       ]
 [ 0.          1.         -0.14814815  0.44444444]
 [ 0.          0.         -4.74074074  0.22222222]]


In [16]:
#type your code here:



 R = 
 [[ 1.          0.          0.5         0.125     ]
 [ 0.          1.         -0.16666667  1.04166667]
 [ 0.          0.          6.16666667 -1.04166667]]


#### (c) Operate on $R$ by the same method as in (b) to obtain the third column of $rref(A)$. First normalize row $3$ of $R$, then subtract multiples of row $3$ from rows $1$ and $2$ to put zeros in the (1, 3) and (2, 3) positions.

In [43]:
R[2,:] = R[2, :] / R[2 ,2]
R[0, :] = R[0, :] - R[0, 2] * R[2, :]
R[1, :] = R[1, :] - R[1, 2] * R[2, :]
print("R = \n",R)

R = 
 [[ 1.         0.         0.         0.5546875]
 [ 0.         1.         0.         0.4375   ]
 [-0.        -0.         1.        -0.046875 ]]


In [17]:
#type your code here:




 R = 
 [[ 1.          0.          0.          0.20945946]
 [ 0.          1.          0.          1.01351351]
 [ 0.          0.          1.         -0.16891892]]


#### (d) Your matrix $R$ should now be transformed into $rref(A)$ (since $A$ is a random $3 \times 4$ matrix, $rref(A)$ is (almost) sure to have rank (3) `np.linalg.matrix_rank(R)`. Check your answer by python with the rref method . If the answer is not the same as the current value of your $R$, go back and redo your calculations.

- use the the built in rref method `sympy.rref()`
- print the output matrix in numpy array type

    - `M = sym.Matrix(A)`
    - `M_rref = M.rref()`
    - `R = np.array((M_rref[0])).astype(np.float64)`

In [49]:
rank = np.linalg.matrix_rank(R)
M = sym.Matrix(A)
M_rref = M.rref()
R = np.array((M_rref[0])).astype(np.float64)

print("rank = \n",rank)
print("The Row echelon form of matrix M \n",R)

rank = 
 3
The Row echelon form of matrix M 
 [[ 1.         0.         0.         0.5546875]
 [ 0.         1.         0.         0.4375   ]
 [ 0.         0.         1.        -0.046875 ]]


In [18]:
#type your code here:

# Use sympy.rref() method 



 rank = 
 3

 The Row echelon form of matrix M 
 [[ 1.          0.          0.          0.20945946]
 [ 0.          1.          0.          1.01351351]
 [ 0.          0.          1.         -0.16891892]]


# Question 5. Matrix Multiplication using Different views

we discussed in the lecture four different ways about product $AB = C$ where $A$ and $B$ are arbitry matrices. If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix, then $C$ is an $m \times p$ matrix:

1. **Standard(row times column):** The standard way of describing a matrix product is to say that $c_(ij)$ equals the dot product of row $i$ of matrix $A$ and column $j$ of matrix $B$. 
 
2. **Columns:** The product of matrix $A$ and column $j$ of matrix $B$ equals column $j$ of matrix  $C$. This tells us that the columns of $C$ are combinations of columns of $A$.

3. **Rows:** The product of row $i$ of matrix $A$ and matrix $B$ equals row $i$ of matrix $C$.So the rows of $C$ are combinations of rows of $B$.

4. **Column times row**: A column of $A$ is an $m \times 1$ vector and a row of $B$ is a $1 \times p$ vector.Their product is a matrix.

In this problem we will use python to perform the matrix multiplication using these different ways, and compute the execution time for each method time.

(Write your code as a function that perform the multiplication for arbitrary size of the matrices $A$ and $B$)

In [12]:
def check_dimension(A, B):
    return A.shape[1] == B.shape[0]

def mat_mul_columns(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    result_mat = np.zeros((m, p))
    ################type your code here#####################
    #C[:,0] = A[:,0]*B[0,0]+A[:,1]*B[1,0]+A[:,2]*B[2,0]
    #C[:,1] = A[:,0]*B[0,1]+A[:,1]*B[1,1]+A[:,2]*B[2,1]
     
    for i in range(n):
        for j in range(p):
            C[:,j] = A[:,i]*B[i,j]+A[:,i]*B[i,j]+A[:,i]*B[i,j]
    
    ########################################################         
    return C

A = np.fix((10*(np.random.rand(300, 300))))
B = np.fix((10*(np.random.rand(300, 300))))

import time

#start_time = time.time()

C_column_times_row =  mat_mul_columns(A, B)
print('C_column_times_row = \n', C_column_times_row)

#start_time = time.time()
print('A @ B = \n', A @ B)


C_column_times_row = 
 [[ 54. 144.  72. ... 126. 162. 162.]
 [ 81. 216. 108. ... 189. 243. 243.]
 [ 54. 144.  72. ... 126. 162. 162.]
 ...
 [ 54. 144.  72. ... 126. 162. 162.]
 [ 81. 216. 108. ... 189. 243. 243.]
 [ 36.  96.  48. ...  84. 108. 108.]]
A @ B = 
 [[6476. 5963. 6447. ... 6454. 6938. 6217.]
 [6295. 6080. 6088. ... 6194. 6462. 6160.]
 [5984. 5390. 5771. ... 6025. 6221. 5869.]
 ...
 [5566. 5599. 5808. ... 5727. 5710. 5569.]
 [6412. 6155. 6374. ... 6739. 6727. 6389.]
 [5854. 5273. 5625. ... 5453. 5827. 5657.]]


In [91]:

def check_dimension(A, B):
    return A.shape[1] == B.shape[0]

def mat_mul_standard(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(p) :
        for j in range(m):
            C[i,j] = np.sum(A[i]*B[:,j])

    ########################################################        
    return C


def mat_mul_columns(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    for j in range(p):
        C[:, j] = np.sum(A * B[:, j], axis=1)

    ########################################################         
    return C

def mat_mul_rows(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(m):
        for j in range(p):
            C[i, j] = np.sum(A[i, :] * B[:, j])
    ########################################################         
    return C



def mat_mul_column_times_row(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    result_mat = np.zeros((m, p))
    ################type your code here#####################
   # C[0] = A[0,0]*B[0]
    #C[1] = A[1,0]*B[0]
    #+
    #C[0] = A[0,1]*B[1]
    #C[1] = A[1,1]*B[1]
    
    for i in range(n):
        for j in range(m):
            C[j] = A[j,i]*B[i]
        result_mat += C
    ########################################################         
    return result_mat

In [92]:
#A = np.array([[12., 7., 3.],[4., 5., 6.],[7., 8., 9.]])
#B = np.array([[5., 8., 1., 2.],[6., 7., 3., 0.],[4., 5., 9., 1.]])

A = np.fix((10*(np.random.rand(300, 300))))
B = np.fix((10*(np.random.rand(300, 300))))

In [93]:
%%time
print('A @ B = \n', A @ B)

A @ B = 
 [[5804. 6096. 5822. ... 6085. 6366. 5580.]
 [5498. 5711. 5453. ... 5377. 5689. 5130.]
 [5939. 6397. 5795. ... 5969. 6080. 5424.]
 ...
 [5970. 6017. 6007. ... 5879. 6158. 5652.]
 [5805. 5729. 5596. ... 5773. 6073. 5406.]
 [6062. 6433. 5896. ... 6405. 6476. 5824.]]
CPU times: total: 0 ns
Wall time: 2 ms


In [94]:
%%time
C_standard = mat_mul_standard(A, B)
print('C_standard = \n', C_standard)

C_standard = 
 [[5804. 6096. 5822. ... 6085. 6366. 5580.]
 [5498. 5711. 5453. ... 5377. 5689. 5130.]
 [5939. 6397. 5795. ... 5969. 6080. 5424.]
 ...
 [5970. 6017. 6007. ... 5879. 6158. 5652.]
 [5805. 5729. 5596. ... 5773. 6073. 5406.]
 [6062. 6433. 5896. ... 6405. 6476. 5824.]]
CPU times: total: 516 ms
Wall time: 617 ms


In [95]:
%%time
C_columns = mat_mul_columns(A, B)
print('C_columns = \n', C_columns)

C_columns = 
 [[5804. 6096. 5822. ... 6085. 6366. 5580.]
 [5498. 5711. 5453. ... 5377. 5689. 5130.]
 [5939. 6397. 5795. ... 5969. 6080. 5424.]
 ...
 [5970. 6017. 6007. ... 5879. 6158. 5652.]
 [5805. 5729. 5596. ... 5773. 6073. 5406.]
 [6062. 6433. 5896. ... 6405. 6476. 5824.]]
CPU times: total: 46.9 ms
Wall time: 64.2 ms


In [96]:
%%time
C_rows = mat_mul_rows(A, B)
print('C_rows = \n', C_rows)

C_rows = 
 [[5804. 6096. 5822. ... 6085. 6366. 5580.]
 [5498. 5711. 5453. ... 5377. 5689. 5130.]
 [5939. 6397. 5795. ... 5969. 6080. 5424.]
 ...
 [5970. 6017. 6007. ... 5879. 6158. 5652.]
 [5805. 5729. 5596. ... 5773. 6073. 5406.]
 [6062. 6433. 5896. ... 6405. 6476. 5824.]]
CPU times: total: 594 ms
Wall time: 750 ms


In [97]:
%%time
C_column_times_row = mat_mul_column_times_row(A, B)
print('C_column_times_row = \n', C_column_times_row)

C_column_times_row = 
 [[5804. 6096. 5822. ... 6085. 6366. 5580.]
 [5498. 5711. 5453. ... 5377. 5689. 5130.]
 [5939. 6397. 5795. ... 5969. 6080. 5424.]
 ...
 [5970. 6017. 6007. ... 5879. 6158. 5652.]
 [5805. 5729. 5596. ... 5773. 6073. 5406.]
 [6062. 6433. 5896. ... 6405. 6476. 5824.]]
CPU times: total: 281 ms
Wall time: 302 ms
